/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as CallbackAuthRouteImport } from './app/callback/auth'
import { Route as pagesprotectedLayoutRouteImport } from './app/(pages)/(protected)/layout'
import { Route as pagesauthPagesLayoutRouteImport } from './app/(pages)/(auth-pages)/layout'
import { Route as pagesauthFlowsLayoutRouteImport } from './app/(pages)/(auth-flows)/layout'
import { Route as pagesprotectedSettingsLayoutRouteImport } from './app/(pages)/(protected)/settings/layout'
import { Route as pagesprotectedPageRouteImport } from './app/(pages)/(protected)/page'
import { Route as pagesprotectedAccountsIdRouteImport } from './app/(pages)/(protected)/accounts/$id'
import { Route as pagesprotectedTransactionsPageRouteImport } from './app/(pages)/(protected)/transactions/page'
import { Route as pagesprotectedSettingsPageRouteImport } from './app/(pages)/(protected)/settings/page'
import { Route as pagesprotectedAccountsPageRouteImport } from './app/(pages)/(protected)/accounts/page'
import { Route as pagesauthPagesSignUpPageRouteImport } from './app/(pages)/(auth-pages)/sign-up/page'
import { Route as pagesauthPagesLoginPageRouteImport } from './app/(pages)/(auth-pages)/login/page'
import { Route as pagesauthPagesForgotPasswordPageRouteImport } from './app/(pages)/(auth-pages)/forgot-password/page'
import { Route as pagesauthFlowsRecoveryPageRouteImport } from './app/(pages)/(auth-flows)/recovery/page'
import { Route as pagesauthFlowsOnboardingPageRouteImport } from './app/(pages)/(auth-flows)/onboarding/page'
import { Route as pagesprotectedSettingsSubscriptionPageRouteImport } from './app/(pages)/(protected)/settings/subscription/page'
import { Route as pagesprotectedSettingsSecurityPageRouteImport } from './app/(pages)/(protected)/settings/security/page'
import { Route as pagesprotectedSettingsDeveloperPageRouteImport } from './app/(pages)/(protected)/settings/developer/page'
import { Route as pagesprotectedSettingsConnectionsPageRouteImport } from './app/(pages)/(protected)/settings/connections/page'
import { Route as pagesprotectedSettingsCategoriesPageRouteImport } from './app/(pages)/(protected)/settings/categories/page'
import { Route as pagesprotectedSettingsAccountPageRouteImport } from './app/(pages)/(protected)/settings/account/page'
import { Route as pagesauthPagesOauthSignInPageRouteImport } from './app/(pages)/(auth-pages)/oauth/sign-in/page'
import { Route as pagesauthPagesOauthConsentPageRouteImport } from './app/(pages)/(auth-pages)/oauth/consent/page'

const CallbackAuthRoute = CallbackAuthRouteImport.update({
  id: '/callback/auth',
  path: '/callback/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesprotectedLayoutRoute = pagesprotectedLayoutRouteImport.update({
  id: '/(pages)/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesauthPagesLayoutRoute = pagesauthPagesLayoutRouteImport.update({
  id: '/(pages)/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesauthFlowsLayoutRoute = pagesauthFlowsLayoutRouteImport.update({
  id: '/(pages)/(auth-flows)',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesprotectedSettingsLayoutRoute =
  pagesprotectedSettingsLayoutRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => pagesprotectedLayoutRoute,
  } as any)
const pagesprotectedPageRoute = pagesprotectedPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => pagesprotectedLayoutRoute,
} as any)
const pagesprotectedAccountsIdRoute =
  pagesprotectedAccountsIdRouteImport.update({
    id: '/accounts/$id',
    path: '/accounts/$id',
    getParentRoute: () => pagesprotectedLayoutRoute,
  } as any)
const pagesprotectedTransactionsPageRoute =
  pagesprotectedTransactionsPageRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => pagesprotectedLayoutRoute,
  } as any)
const pagesprotectedSettingsPageRoute =
  pagesprotectedSettingsPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => pagesprotectedSettingsLayoutRoute,
  } as any)
const pagesprotectedAccountsPageRoute =
  pagesprotectedAccountsPageRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => pagesprotectedLayoutRoute,
  } as any)
const pagesauthPagesSignUpPageRoute =
  pagesauthPagesSignUpPageRouteImport.update({
    id: '/sign-up/',
    path: '/sign-up/',
    getParentRoute: () => pagesauthPagesLayoutRoute,
  } as any)
const pagesauthPagesLoginPageRoute = pagesauthPagesLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => pagesauthPagesLayoutRoute,
} as any)
const pagesauthPagesForgotPasswordPageRoute =
  pagesauthPagesForgotPasswordPageRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => pagesauthPagesLayoutRoute,
  } as any)
const pagesauthFlowsRecoveryPageRoute =
  pagesauthFlowsRecoveryPageRouteImport.update({
    id: '/recovery/',
    path: '/recovery/',
    getParentRoute: () => pagesauthFlowsLayoutRoute,
  } as any)
const pagesauthFlowsOnboardingPageRoute =
  pagesauthFlowsOnboardingPageRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => pagesauthFlowsLayoutRoute,
  } as any)
const pagesprotectedSettingsSubscriptionPageRoute =
  pagesprotectedSettingsSubscriptionPageRouteImport.update({
    id: '/subscription/',
    path: '/subscription/',
    getParentRoute: () => pagesprotectedSettingsLayoutRoute,
  } as any)
const pagesprotectedSettingsSecurityPageRoute =
  pagesprotectedSettingsSecurityPageRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => pagesprotectedSettingsLayoutRoute,
  } as any)
const pagesprotectedSettingsDeveloperPageRoute =
  pagesprotectedSettingsDeveloperPageRouteImport.update({
    id: '/developer/',
    path: '/developer/',
    getParentRoute: () => pagesprotectedSettingsLayoutRoute,
  } as any)
const pagesprotectedSettingsConnectionsPageRoute =
  pagesprotectedSettingsConnectionsPageRouteImport.update({
    id: '/connections/',
    path: '/connections/',
    getParentRoute: () => pagesprotectedSettingsLayoutRoute,
  } as any)
const pagesprotectedSettingsCategoriesPageRoute =
  pagesprotectedSettingsCategoriesPageRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => pagesprotectedSettingsLayoutRoute,
  } as any)
const pagesprotectedSettingsAccountPageRoute =
  pagesprotectedSettingsAccountPageRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => pagesprotectedSettingsLayoutRoute,
  } as any)
const pagesauthPagesOauthSignInPageRoute =
  pagesauthPagesOauthSignInPageRouteImport.update({
    id: '/oauth/sign-in/',
    path: '/oauth/sign-in/',
    getParentRoute: () => pagesauthPagesLayoutRoute,
  } as any)
const pagesauthPagesOauthConsentPageRoute =
  pagesauthPagesOauthConsentPageRouteImport.update({
    id: '/oauth/consent/',
    path: '/oauth/consent/',
    getParentRoute: () => pagesauthPagesLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/callback/auth': typeof CallbackAuthRoute
  '/': typeof pagesprotectedPageRoute
  '/settings': typeof pagesprotectedSettingsLayoutRouteWithChildren
  '/onboarding/': typeof pagesauthFlowsOnboardingPageRoute
  '/recovery/': typeof pagesauthFlowsRecoveryPageRoute
  '/forgot-password/': typeof pagesauthPagesForgotPasswordPageRoute
  '/login/': typeof pagesauthPagesLoginPageRoute
  '/sign-up/': typeof pagesauthPagesSignUpPageRoute
  '/accounts/': typeof pagesprotectedAccountsPageRoute
  '/settings/': typeof pagesprotectedSettingsPageRoute
  '/transactions/': typeof pagesprotectedTransactionsPageRoute
  '/accounts/$id': typeof pagesprotectedAccountsIdRoute
  '/oauth/consent/': typeof pagesauthPagesOauthConsentPageRoute
  '/oauth/sign-in/': typeof pagesauthPagesOauthSignInPageRoute
  '/settings/account/': typeof pagesprotectedSettingsAccountPageRoute
  '/settings/categories/': typeof pagesprotectedSettingsCategoriesPageRoute
  '/settings/connections/': typeof pagesprotectedSettingsConnectionsPageRoute
  '/settings/developer/': typeof pagesprotectedSettingsDeveloperPageRoute
  '/settings/security/': typeof pagesprotectedSettingsSecurityPageRoute
  '/settings/subscription/': typeof pagesprotectedSettingsSubscriptionPageRoute
}
export interface FileRoutesByTo {
  '/callback/auth': typeof CallbackAuthRoute
  '/': typeof pagesprotectedPageRoute
  '/onboarding': typeof pagesauthFlowsOnboardingPageRoute
  '/recovery': typeof pagesauthFlowsRecoveryPageRoute
  '/forgot-password': typeof pagesauthPagesForgotPasswordPageRoute
  '/login': typeof pagesauthPagesLoginPageRoute
  '/sign-up': typeof pagesauthPagesSignUpPageRoute
  '/accounts': typeof pagesprotectedAccountsPageRoute
  '/settings': typeof pagesprotectedSettingsPageRoute
  '/transactions': typeof pagesprotectedTransactionsPageRoute
  '/accounts/$id': typeof pagesprotectedAccountsIdRoute
  '/oauth/consent': typeof pagesauthPagesOauthConsentPageRoute
  '/oauth/sign-in': typeof pagesauthPagesOauthSignInPageRoute
  '/settings/account': typeof pagesprotectedSettingsAccountPageRoute
  '/settings/categories': typeof pagesprotectedSettingsCategoriesPageRoute
  '/settings/connections': typeof pagesprotectedSettingsConnectionsPageRoute
  '/settings/developer': typeof pagesprotectedSettingsDeveloperPageRoute
  '/settings/security': typeof pagesprotectedSettingsSecurityPageRoute
  '/settings/subscription': typeof pagesprotectedSettingsSubscriptionPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(pages)/(auth-flows)': typeof pagesauthFlowsLayoutRouteWithChildren
  '/(pages)/(auth-pages)': typeof pagesauthPagesLayoutRouteWithChildren
  '/(pages)/(protected)': typeof pagesprotectedLayoutRouteWithChildren
  '/callback/auth': typeof CallbackAuthRoute
  '/(pages)/(protected)/': typeof pagesprotectedPageRoute
  '/(pages)/(protected)/settings': typeof pagesprotectedSettingsLayoutRouteWithChildren
  '/(pages)/(auth-flows)/onboarding/': typeof pagesauthFlowsOnboardingPageRoute
  '/(pages)/(auth-flows)/recovery/': typeof pagesauthFlowsRecoveryPageRoute
  '/(pages)/(auth-pages)/forgot-password/': typeof pagesauthPagesForgotPasswordPageRoute
  '/(pages)/(auth-pages)/login/': typeof pagesauthPagesLoginPageRoute
  '/(pages)/(auth-pages)/sign-up/': typeof pagesauthPagesSignUpPageRoute
  '/(pages)/(protected)/accounts/': typeof pagesprotectedAccountsPageRoute
  '/(pages)/(protected)/settings/': typeof pagesprotectedSettingsPageRoute
  '/(pages)/(protected)/transactions/': typeof pagesprotectedTransactionsPageRoute
  '/(pages)/(protected)/accounts/$id': typeof pagesprotectedAccountsIdRoute
  '/(pages)/(auth-pages)/oauth/consent/': typeof pagesauthPagesOauthConsentPageRoute
  '/(pages)/(auth-pages)/oauth/sign-in/': typeof pagesauthPagesOauthSignInPageRoute
  '/(pages)/(protected)/settings/account/': typeof pagesprotectedSettingsAccountPageRoute
  '/(pages)/(protected)/settings/categories/': typeof pagesprotectedSettingsCategoriesPageRoute
  '/(pages)/(protected)/settings/connections/': typeof pagesprotectedSettingsConnectionsPageRoute
  '/(pages)/(protected)/settings/developer/': typeof pagesprotectedSettingsDeveloperPageRoute
  '/(pages)/(protected)/settings/security/': typeof pagesprotectedSettingsSecurityPageRoute
  '/(pages)/(protected)/settings/subscription/': typeof pagesprotectedSettingsSubscriptionPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/callback/auth'
    | '/'
    | '/settings'
    | '/onboarding/'
    | '/recovery/'
    | '/forgot-password/'
    | '/login/'
    | '/sign-up/'
    | '/accounts/'
    | '/settings/'
    | '/transactions/'
    | '/accounts/$id'
    | '/oauth/consent/'
    | '/oauth/sign-in/'
    | '/settings/account/'
    | '/settings/categories/'
    | '/settings/connections/'
    | '/settings/developer/'
    | '/settings/security/'
    | '/settings/subscription/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback/auth'
    | '/'
    | '/onboarding'
    | '/recovery'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/accounts'
    | '/settings'
    | '/transactions'
    | '/accounts/$id'
    | '/oauth/consent'
    | '/oauth/sign-in'
    | '/settings/account'
    | '/settings/categories'
    | '/settings/connections'
    | '/settings/developer'
    | '/settings/security'
    | '/settings/subscription'
  id:
    | '__root__'
    | '/(pages)/(auth-flows)'
    | '/(pages)/(auth-pages)'
    | '/(pages)/(protected)'
    | '/callback/auth'
    | '/(pages)/(protected)/'
    | '/(pages)/(protected)/settings'
    | '/(pages)/(auth-flows)/onboarding/'
    | '/(pages)/(auth-flows)/recovery/'
    | '/(pages)/(auth-pages)/forgot-password/'
    | '/(pages)/(auth-pages)/login/'
    | '/(pages)/(auth-pages)/sign-up/'
    | '/(pages)/(protected)/accounts/'
    | '/(pages)/(protected)/settings/'
    | '/(pages)/(protected)/transactions/'
    | '/(pages)/(protected)/accounts/$id'
    | '/(pages)/(auth-pages)/oauth/consent/'
    | '/(pages)/(auth-pages)/oauth/sign-in/'
    | '/(pages)/(protected)/settings/account/'
    | '/(pages)/(protected)/settings/categories/'
    | '/(pages)/(protected)/settings/connections/'
    | '/(pages)/(protected)/settings/developer/'
    | '/(pages)/(protected)/settings/security/'
    | '/(pages)/(protected)/settings/subscription/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  pagesauthFlowsLayoutRoute: typeof pagesauthFlowsLayoutRouteWithChildren
  pagesauthPagesLayoutRoute: typeof pagesauthPagesLayoutRouteWithChildren
  pagesprotectedLayoutRoute: typeof pagesprotectedLayoutRouteWithChildren
  CallbackAuthRoute: typeof CallbackAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback/auth': {
      id: '/callback/auth'
      path: '/callback/auth'
      fullPath: '/callback/auth'
      preLoaderRoute: typeof CallbackAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/(protected)': {
      id: '/(pages)/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagesprotectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/(auth-pages)': {
      id: '/(pages)/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagesauthPagesLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/(auth-flows)': {
      id: '/(pages)/(auth-flows)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagesauthFlowsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/(protected)/settings': {
      id: '/(pages)/(protected)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof pagesprotectedSettingsLayoutRouteImport
      parentRoute: typeof pagesprotectedLayoutRoute
    }
    '/(pages)/(protected)/': {
      id: '/(pages)/(protected)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof pagesprotectedPageRouteImport
      parentRoute: typeof pagesprotectedLayoutRoute
    }
    '/(pages)/(protected)/accounts/$id': {
      id: '/(pages)/(protected)/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof pagesprotectedAccountsIdRouteImport
      parentRoute: typeof pagesprotectedLayoutRoute
    }
    '/(pages)/(protected)/transactions/': {
      id: '/(pages)/(protected)/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof pagesprotectedTransactionsPageRouteImport
      parentRoute: typeof pagesprotectedLayoutRoute
    }
    '/(pages)/(protected)/settings/': {
      id: '/(pages)/(protected)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof pagesprotectedSettingsPageRouteImport
      parentRoute: typeof pagesprotectedSettingsLayoutRoute
    }
    '/(pages)/(protected)/accounts/': {
      id: '/(pages)/(protected)/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof pagesprotectedAccountsPageRouteImport
      parentRoute: typeof pagesprotectedLayoutRoute
    }
    '/(pages)/(auth-pages)/sign-up/': {
      id: '/(pages)/(auth-pages)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof pagesauthPagesSignUpPageRouteImport
      parentRoute: typeof pagesauthPagesLayoutRoute
    }
    '/(pages)/(auth-pages)/login/': {
      id: '/(pages)/(auth-pages)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof pagesauthPagesLoginPageRouteImport
      parentRoute: typeof pagesauthPagesLayoutRoute
    }
    '/(pages)/(auth-pages)/forgot-password/': {
      id: '/(pages)/(auth-pages)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof pagesauthPagesForgotPasswordPageRouteImport
      parentRoute: typeof pagesauthPagesLayoutRoute
    }
    '/(pages)/(auth-flows)/recovery/': {
      id: '/(pages)/(auth-flows)/recovery/'
      path: '/recovery'
      fullPath: '/recovery/'
      preLoaderRoute: typeof pagesauthFlowsRecoveryPageRouteImport
      parentRoute: typeof pagesauthFlowsLayoutRoute
    }
    '/(pages)/(auth-flows)/onboarding/': {
      id: '/(pages)/(auth-flows)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof pagesauthFlowsOnboardingPageRouteImport
      parentRoute: typeof pagesauthFlowsLayoutRoute
    }
    '/(pages)/(protected)/settings/subscription/': {
      id: '/(pages)/(protected)/settings/subscription/'
      path: '/subscription'
      fullPath: '/settings/subscription/'
      preLoaderRoute: typeof pagesprotectedSettingsSubscriptionPageRouteImport
      parentRoute: typeof pagesprotectedSettingsLayoutRoute
    }
    '/(pages)/(protected)/settings/security/': {
      id: '/(pages)/(protected)/settings/security/'
      path: '/security'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof pagesprotectedSettingsSecurityPageRouteImport
      parentRoute: typeof pagesprotectedSettingsLayoutRoute
    }
    '/(pages)/(protected)/settings/developer/': {
      id: '/(pages)/(protected)/settings/developer/'
      path: '/developer'
      fullPath: '/settings/developer/'
      preLoaderRoute: typeof pagesprotectedSettingsDeveloperPageRouteImport
      parentRoute: typeof pagesprotectedSettingsLayoutRoute
    }
    '/(pages)/(protected)/settings/connections/': {
      id: '/(pages)/(protected)/settings/connections/'
      path: '/connections'
      fullPath: '/settings/connections/'
      preLoaderRoute: typeof pagesprotectedSettingsConnectionsPageRouteImport
      parentRoute: typeof pagesprotectedSettingsLayoutRoute
    }
    '/(pages)/(protected)/settings/categories/': {
      id: '/(pages)/(protected)/settings/categories/'
      path: '/categories'
      fullPath: '/settings/categories/'
      preLoaderRoute: typeof pagesprotectedSettingsCategoriesPageRouteImport
      parentRoute: typeof pagesprotectedSettingsLayoutRoute
    }
    '/(pages)/(protected)/settings/account/': {
      id: '/(pages)/(protected)/settings/account/'
      path: '/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof pagesprotectedSettingsAccountPageRouteImport
      parentRoute: typeof pagesprotectedSettingsLayoutRoute
    }
    '/(pages)/(auth-pages)/oauth/sign-in/': {
      id: '/(pages)/(auth-pages)/oauth/sign-in/'
      path: '/oauth/sign-in'
      fullPath: '/oauth/sign-in/'
      preLoaderRoute: typeof pagesauthPagesOauthSignInPageRouteImport
      parentRoute: typeof pagesauthPagesLayoutRoute
    }
    '/(pages)/(auth-pages)/oauth/consent/': {
      id: '/(pages)/(auth-pages)/oauth/consent/'
      path: '/oauth/consent'
      fullPath: '/oauth/consent/'
      preLoaderRoute: typeof pagesauthPagesOauthConsentPageRouteImport
      parentRoute: typeof pagesauthPagesLayoutRoute
    }
  }
}

interface pagesauthFlowsLayoutRouteChildren {
  pagesauthFlowsOnboardingPageRoute: typeof pagesauthFlowsOnboardingPageRoute
  pagesauthFlowsRecoveryPageRoute: typeof pagesauthFlowsRecoveryPageRoute
}

const pagesauthFlowsLayoutRouteChildren: pagesauthFlowsLayoutRouteChildren = {
  pagesauthFlowsOnboardingPageRoute: pagesauthFlowsOnboardingPageRoute,
  pagesauthFlowsRecoveryPageRoute: pagesauthFlowsRecoveryPageRoute,
}

const pagesauthFlowsLayoutRouteWithChildren =
  pagesauthFlowsLayoutRoute._addFileChildren(pagesauthFlowsLayoutRouteChildren)

interface pagesauthPagesLayoutRouteChildren {
  pagesauthPagesForgotPasswordPageRoute: typeof pagesauthPagesForgotPasswordPageRoute
  pagesauthPagesLoginPageRoute: typeof pagesauthPagesLoginPageRoute
  pagesauthPagesSignUpPageRoute: typeof pagesauthPagesSignUpPageRoute
  pagesauthPagesOauthConsentPageRoute: typeof pagesauthPagesOauthConsentPageRoute
  pagesauthPagesOauthSignInPageRoute: typeof pagesauthPagesOauthSignInPageRoute
}

const pagesauthPagesLayoutRouteChildren: pagesauthPagesLayoutRouteChildren = {
  pagesauthPagesForgotPasswordPageRoute: pagesauthPagesForgotPasswordPageRoute,
  pagesauthPagesLoginPageRoute: pagesauthPagesLoginPageRoute,
  pagesauthPagesSignUpPageRoute: pagesauthPagesSignUpPageRoute,
  pagesauthPagesOauthConsentPageRoute: pagesauthPagesOauthConsentPageRoute,
  pagesauthPagesOauthSignInPageRoute: pagesauthPagesOauthSignInPageRoute,
}

const pagesauthPagesLayoutRouteWithChildren =
  pagesauthPagesLayoutRoute._addFileChildren(pagesauthPagesLayoutRouteChildren)

interface pagesprotectedSettingsLayoutRouteChildren {
  pagesprotectedSettingsPageRoute: typeof pagesprotectedSettingsPageRoute
  pagesprotectedSettingsAccountPageRoute: typeof pagesprotectedSettingsAccountPageRoute
  pagesprotectedSettingsCategoriesPageRoute: typeof pagesprotectedSettingsCategoriesPageRoute
  pagesprotectedSettingsConnectionsPageRoute: typeof pagesprotectedSettingsConnectionsPageRoute
  pagesprotectedSettingsDeveloperPageRoute: typeof pagesprotectedSettingsDeveloperPageRoute
  pagesprotectedSettingsSecurityPageRoute: typeof pagesprotectedSettingsSecurityPageRoute
  pagesprotectedSettingsSubscriptionPageRoute: typeof pagesprotectedSettingsSubscriptionPageRoute
}

const pagesprotectedSettingsLayoutRouteChildren: pagesprotectedSettingsLayoutRouteChildren =
  {
    pagesprotectedSettingsPageRoute: pagesprotectedSettingsPageRoute,
    pagesprotectedSettingsAccountPageRoute:
      pagesprotectedSettingsAccountPageRoute,
    pagesprotectedSettingsCategoriesPageRoute:
      pagesprotectedSettingsCategoriesPageRoute,
    pagesprotectedSettingsConnectionsPageRoute:
      pagesprotectedSettingsConnectionsPageRoute,
    pagesprotectedSettingsDeveloperPageRoute:
      pagesprotectedSettingsDeveloperPageRoute,
    pagesprotectedSettingsSecurityPageRoute:
      pagesprotectedSettingsSecurityPageRoute,
    pagesprotectedSettingsSubscriptionPageRoute:
      pagesprotectedSettingsSubscriptionPageRoute,
  }

const pagesprotectedSettingsLayoutRouteWithChildren =
  pagesprotectedSettingsLayoutRoute._addFileChildren(
    pagesprotectedSettingsLayoutRouteChildren,
  )

interface pagesprotectedLayoutRouteChildren {
  pagesprotectedPageRoute: typeof pagesprotectedPageRoute
  pagesprotectedSettingsLayoutRoute: typeof pagesprotectedSettingsLayoutRouteWithChildren
  pagesprotectedAccountsPageRoute: typeof pagesprotectedAccountsPageRoute
  pagesprotectedTransactionsPageRoute: typeof pagesprotectedTransactionsPageRoute
  pagesprotectedAccountsIdRoute: typeof pagesprotectedAccountsIdRoute
}

const pagesprotectedLayoutRouteChildren: pagesprotectedLayoutRouteChildren = {
  pagesprotectedPageRoute: pagesprotectedPageRoute,
  pagesprotectedSettingsLayoutRoute:
    pagesprotectedSettingsLayoutRouteWithChildren,
  pagesprotectedAccountsPageRoute: pagesprotectedAccountsPageRoute,
  pagesprotectedTransactionsPageRoute: pagesprotectedTransactionsPageRoute,
  pagesprotectedAccountsIdRoute: pagesprotectedAccountsIdRoute,
}

const pagesprotectedLayoutRouteWithChildren =
  pagesprotectedLayoutRoute._addFileChildren(pagesprotectedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  pagesauthFlowsLayoutRoute: pagesauthFlowsLayoutRouteWithChildren,
  pagesauthPagesLayoutRoute: pagesauthPagesLayoutRouteWithChildren,
  pagesprotectedLayoutRoute: pagesprotectedLayoutRouteWithChildren,
  CallbackAuthRoute: CallbackAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
