import { sql } from "drizzle-orm";

import { country } from "../src/db/schema/countries";
import { createDb } from "../src/lib/db";

const countries = [
  { code: "AD", name: "Andorra", currency_code: "EUR" },
  { code: "AE", name: "United Arab Emirates", currency_code: "AED" },
  { code: "AF", name: "Afghanistan", currency_code: "AFN" },
  { code: "AG", name: "Antigua and Barbuda", currency_code: "XCD" },
  { code: "AI", name: "Anguilla", currency_code: "XCD" },
  { code: "AL", name: "Albania", currency_code: "ALL" },
  { code: "AM", name: "Armenia", currency_code: "AMD" },
  { code: "AO", name: "Angola", currency_code: "AOA" },
  { code: "AR", name: "Argentina", currency_code: "ARS" },
  { code: "AS", name: "American Samoa", currency_code: "USD" },
  { code: "AT", name: "Austria", currency_code: "EUR" },
  { code: "AU", name: "Australia", currency_code: "AUD" },
  { code: "AW", name: "Aruba", currency_code: "AWG" },
  { code: "AX", name: "Åland Islands", currency_code: "EUR" },
  { code: "AZ", name: "Azerbaijan", currency_code: "AZN" },
  { code: "BA", name: "Bosnia and Herzegovina", currency_code: "BAM" },
  { code: "BB", name: "Barbados", currency_code: "BBD" },
  { code: "BD", name: "Bangladesh", currency_code: "BDT" },
  { code: "BE", name: "Belgium", currency_code: "EUR" },
  { code: "BF", name: "Burkina Faso", currency_code: "XOF" },
  { code: "BG", name: "Bulgaria", currency_code: "BGN" },
  { code: "BH", name: "Bahrain", currency_code: "BHD" },
  { code: "BI", name: "Burundi", currency_code: "BIF" },
  { code: "BJ", name: "Benin", currency_code: "XOF" },
  { code: "BL", name: "Saint Barthélemy", currency_code: "EUR" },
  { code: "BM", name: "Bermuda", currency_code: "BMD" },
  { code: "BN", name: "Brunei Darussalam", currency_code: "BND" },
  { code: "BO", name: "Bolivia", currency_code: "BOB" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", currency_code: "USD" },
  { code: "BR", name: "Brazil", currency_code: "BRL" },
  { code: "BS", name: "Bahamas", currency_code: "BSD" },
  { code: "BT", name: "Bhutan", currency_code: "BTN" },
  { code: "BV", name: "Bouvet Island", currency_code: "NOK" },
  { code: "BW", name: "Botswana", currency_code: "BWP" },
  { code: "BY", name: "Belarus", currency_code: "BYN" },
  { code: "BZ", name: "Belize", currency_code: "BZD" },
  { code: "CA", name: "Canada", currency_code: "CAD" },
  { code: "CC", name: "Cocos (Keeling) Islands", currency_code: "AUD" },
  { code: "CD", name: "Congo, Democratic Republic of the", currency_code: "CDF" },
  { code: "CF", name: "Central African Republic", currency_code: "XAF" },
  { code: "CG", name: "Congo", currency_code: "XAF" },
  { code: "CH", name: "Switzerland", currency_code: "CHF" },
  { code: "CI", name: "Côte d'Ivoire", currency_code: "XOF" },
  { code: "CK", name: "Cook Islands", currency_code: "NZD" },
  { code: "CL", name: "Chile", currency_code: "CLP" },
  { code: "CM", name: "Cameroon", currency_code: "XAF" },
  { code: "CN", name: "China", currency_code: "CNY" },
  { code: "CO", name: "Colombia", currency_code: "COP" },
  { code: "CR", name: "Costa Rica", currency_code: "CRC" },
  { code: "CU", name: "Cuba", currency_code: "CUP" },
  { code: "CV", name: "Cabo Verde", currency_code: "CVE" },
  { code: "CW", name: "Curaçao", currency_code: "ANG" },
  { code: "CX", name: "Christmas Island", currency_code: "AUD" },
  { code: "CY", name: "Cyprus", currency_code: "EUR" },
  { code: "CZ", name: "Czechia", currency_code: "CZK" },
  { code: "DE", name: "Germany", currency_code: "EUR" },
  { code: "DJ", name: "Djibouti", currency_code: "DJF" },
  { code: "DK", name: "Denmark", currency_code: "DKK" },
  { code: "DM", name: "Dominica", currency_code: "XCD" },
  { code: "DO", name: "Dominican Republic", currency_code: "DOP" },
  { code: "DZ", name: "Algeria", currency_code: "DZD" },
  { code: "EC", name: "Ecuador", currency_code: "USD" },
  { code: "EE", name: "Estonia", currency_code: "EUR" },
  { code: "EG", name: "Egypt", currency_code: "EGP" },
  { code: "EH", name: "Western Sahara", currency_code: "MAD" },
  { code: "ER", name: "Eritrea", currency_code: "ERN" },
  { code: "ES", name: "Spain", currency_code: "EUR" },
  { code: "ET", name: "Ethiopia", currency_code: "ETB" },
  { code: "FI", name: "Finland", currency_code: "EUR" },
  { code: "FJ", name: "Fiji", currency_code: "FJD" },
  { code: "FM", name: "Micronesia", currency_code: "USD" },
  { code: "FO", name: "Faroe Islands", currency_code: "DKK" },
  { code: "FR", name: "France", currency_code: "EUR" },
  { code: "GA", name: "Gabon", currency_code: "XAF" },
  { code: "GB", name: "United Kingdom", currency_code: "GBP" },
  { code: "GD", name: "Grenada", currency_code: "XCD" },
  { code: "GE", name: "Georgia", currency_code: "GEL" },
  { code: "GF", name: "French Guiana", currency_code: "EUR" },
  { code: "GG", name: "Guernsey", currency_code: "GBP" },
  { code: "GH", name: "Ghana", currency_code: "GHS" },
  { code: "GI", name: "Gibraltar", currency_code: "GIP" },
  { code: "GL", name: "Greenland", currency_code: "DKK" },
  { code: "GM", name: "Gambia", currency_code: "GMD" },
  { code: "GN", name: "Guinea", currency_code: "GNF" },
  { code: "GP", name: "Guadeloupe", currency_code: "EUR" },
  { code: "GQ", name: "Equatorial Guinea", currency_code: "XAF" },
  { code: "GR", name: "Greece", currency_code: "EUR" },
  { code: "GT", name: "Guatemala", currency_code: "GTQ" },
  { code: "GU", name: "Guam", currency_code: "USD" },
  { code: "GW", name: "Guinea-Bissau", currency_code: "XOF" },
  { code: "GY", name: "Guyana", currency_code: "GYD" },
  { code: "HK", name: "Hong Kong", currency_code: "HKD" },
  { code: "HM", name: "Heard Island and McDonald Islands", currency_code: "AUD" },
  { code: "HN", name: "Honduras", currency_code: "HNL" },
  { code: "HR", name: "Croatia", currency_code: "EUR" },
  { code: "HT", name: "Haiti", currency_code: "HTG" },
  { code: "HU", name: "Hungary", currency_code: "HUF" },
  { code: "ID", name: "Indonesia", currency_code: "IDR" },
  { code: "IE", name: "Ireland", currency_code: "EUR" },
  { code: "IL", name: "Israel", currency_code: "ILS" },
  { code: "IM", name: "Isle of Man", currency_code: "GBP" },
  { code: "IN", name: "India", currency_code: "INR" },
  { code: "IO", name: "British Indian Ocean Territory", currency_code: "USD" },
  { code: "IQ", name: "Iraq", currency_code: "IQD" },
  { code: "IR", name: "Iran", currency_code: "IRR" },
  { code: "IS", name: "Iceland", currency_code: "ISK" },
  { code: "IT", name: "Italy", currency_code: "EUR" },
  { code: "JE", name: "Jersey", currency_code: "GBP" },
  { code: "JM", name: "Jamaica", currency_code: "JMD" },
  { code: "JO", name: "Jordan", currency_code: "JOD" },
  { code: "JP", name: "Japan", currency_code: "JPY" },
  { code: "KE", name: "Kenya", currency_code: "KES" },
  { code: "KG", name: "Kyrgyzstan", currency_code: "KGS" },
  { code: "KH", name: "Cambodia", currency_code: "KHR" },
  { code: "KI", name: "Kiribati", currency_code: "AUD" },
  { code: "KM", name: "Comoros", currency_code: "KMF" },
  { code: "KN", name: "Saint Kitts and Nevis", currency_code: "XCD" },
  { code: "KP", name: "Korea, Democratic People's Republic of", currency_code: "KPW" },
  { code: "KR", name: "Korea, Republic of", currency_code: "KRW" },
  { code: "KW", name: "Kuwait", currency_code: "KWD" },
  { code: "KY", name: "Cayman Islands", currency_code: "KYD" },
  { code: "KZ", name: "Kazakhstan", currency_code: "KZT" },
  { code: "LA", name: "Lao People's Democratic Republic", currency_code: "LAK" },
  { code: "LB", name: "Lebanon", currency_code: "LBP" },
  { code: "LC", name: "Saint Lucia", currency_code: "XCD" },
  { code: "LI", name: "Liechtenstein", currency_code: "CHF" },
  { code: "LK", name: "Sri Lanka", currency_code: "LKR" },
  { code: "LR", name: "Liberia", currency_code: "LRD" },
  { code: "LS", name: "Lesotho", currency_code: "LSL" },
  { code: "LT", name: "Lithuania", currency_code: "EUR" },
  { code: "LU", name: "Luxembourg", currency_code: "EUR" },
  { code: "LV", name: "Latvia", currency_code: "EUR" },
  { code: "LY", name: "Libya", currency_code: "LYD" },
  { code: "MA", name: "Morocco", currency_code: "MAD" },
  { code: "MC", name: "Monaco", currency_code: "EUR" },
  { code: "MD", name: "Moldova", currency_code: "MDL" },
  { code: "ME", name: "Montenegro", currency_code: "EUR" },
  { code: "MF", name: "Saint Martin (French part)", currency_code: "EUR" },
  { code: "MG", name: "Madagascar", currency_code: "MGA" },
  { code: "MH", name: "Marshall Islands", currency_code: "USD" },
  { code: "MK", name: "North Macedonia", currency_code: "MKD" },
  { code: "ML", name: "Mali", currency_code: "XOF" },
  { code: "MM", name: "Myanmar", currency_code: "MMK" },
  { code: "MN", name: "Mongolia", currency_code: "MNT" },
  { code: "MO", name: "Macao", currency_code: "MOP" },
  { code: "MP", name: "Northern Mariana Islands", currency_code: "USD" },
  { code: "MQ", name: "Martinique", currency_code: "EUR" },
  { code: "MR", name: "Mauritania", currency_code: "MRU" },
  { code: "MS", name: "Montserrat", currency_code: "XCD" },
  { code: "MT", name: "Malta", currency_code: "EUR" },
  { code: "MU", name: "Mauritius", currency_code: "MUR" },
  { code: "MV", name: "Maldives", currency_code: "MVR" },
  { code: "MW", name: "Malawi", currency_code: "MWK" },
  { code: "MX", name: "Mexico", currency_code: "MXN" },
  { code: "MY", name: "Malaysia", currency_code: "MYR" },
  { code: "MZ", name: "Mozambique", currency_code: "MZN" },
  { code: "NA", name: "Namibia", currency_code: "NAD" },
  { code: "NC", name: "New Caledonia", currency_code: "XPF" },
  { code: "NE", name: "Niger", currency_code: "XOF" },
  { code: "NF", name: "Norfolk Island", currency_code: "AUD" },
  { code: "NG", name: "Nigeria", currency_code: "NGN" },
  { code: "NI", name: "Nicaragua", currency_code: "NIO" },
  { code: "NL", name: "Netherlands", currency_code: "EUR" },
  { code: "NO", name: "Norway", currency_code: "NOK" },
  { code: "NP", name: "Nepal", currency_code: "NPR" },
  { code: "NR", name: "Nauru", currency_code: "AUD" },
  { code: "NU", name: "Niue", currency_code: "NZD" },
  { code: "NZ", name: "New Zealand", currency_code: "NZD" },
  { code: "OM", name: "Oman", currency_code: "OMR" },
  { code: "PA", name: "Panama", currency_code: "PAB" },
  { code: "PE", name: "Peru", currency_code: "PEN" },
  { code: "PF", name: "French Polynesia", currency_code: "XPF" },
  { code: "PG", name: "Papua New Guinea", currency_code: "PGK" },
  { code: "PH", name: "Philippines", currency_code: "PHP" },
  { code: "PK", name: "Pakistan", currency_code: "PKR" },
  { code: "PL", name: "Poland", currency_code: "PLN" },
  { code: "PM", name: "Saint Pierre and Miquelon", currency_code: "EUR" },
  { code: "PN", name: "Pitcairn", currency_code: "NZD" },
  { code: "PR", name: "Puerto Rico", currency_code: "USD" },
  { code: "PS", name: "Palestine, State of", currency_code: "ILS" },
  { code: "PT", name: "Portugal", currency_code: "EUR" },
  { code: "PW", name: "Palau", currency_code: "USD" },
  { code: "PY", name: "Paraguay", currency_code: "PYG" },
  { code: "QA", name: "Qatar", currency_code: "QAR" },
  { code: "RE", name: "Réunion", currency_code: "EUR" },
  { code: "RO", name: "Romania", currency_code: "RON" },
  { code: "RS", name: "Serbia", currency_code: "RSD" },
  { code: "RU", name: "Russian Federation", currency_code: "RUB" },
  { code: "RW", name: "Rwanda", currency_code: "RWF" },
  { code: "SA", name: "Saudi Arabia", currency_code: "SAR" },
  { code: "SB", name: "Solomon Islands", currency_code: "SBD" },
  { code: "SC", name: "Seychelles", currency_code: "SCR" },
  { code: "SD", name: "Sudan", currency_code: "SDG" },
  { code: "SE", name: "Sweden", currency_code: "SEK" },
  { code: "SG", name: "Singapore", currency_code: "SGD" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", currency_code: "SHP" },
  { code: "SI", name: "Slovenia", currency_code: "EUR" },
  { code: "SJ", name: "Svalbard and Jan Mayen", currency_code: "NOK" },
  { code: "SK", name: "Slovakia", currency_code: "EUR" },
  { code: "SL", name: "Sierra Leone", currency_code: "SLE" },
  { code: "SM", name: "San Marino", currency_code: "EUR" },
  { code: "SN", name: "Senegal", currency_code: "XOF" },
  { code: "SO", name: "Somalia", currency_code: "SOS" },
  { code: "SR", name: "Suriname", currency_code: "SRD" },
  { code: "SS", name: "South Sudan", currency_code: "SSP" },
  { code: "ST", name: "Sao Tome and Principe", currency_code: "STN" },
  { code: "SV", name: "El Salvador", currency_code: "USD" },
  { code: "SX", name: "Sint Maarten (Dutch part)", currency_code: "ANG" },
  { code: "SY", name: "Syrian Arab Republic", currency_code: "SYP" },
  { code: "SZ", name: "Eswatini", currency_code: "SZL" },
  { code: "TC", name: "Turks and Caicos Islands", currency_code: "USD" },
  { code: "TD", name: "Chad", currency_code: "XAF" },
  { code: "TF", name: "French Southern Territories", currency_code: "EUR" },
  { code: "TG", name: "Togo", currency_code: "XOF" },
  { code: "TH", name: "Thailand", currency_code: "THB" },
  { code: "TJ", name: "Tajikistan", currency_code: "TJS" },
  { code: "TK", name: "Tokelau", currency_code: "NZD" },
  { code: "TL", name: "Timor-Leste", currency_code: "USD" },
  { code: "TM", name: "Turkmenistan", currency_code: "TMT" },
  { code: "TN", name: "Tunisia", currency_code: "TND" },
  { code: "TO", name: "Tonga", currency_code: "TOP" },
  { code: "TR", name: "Türkiye", currency_code: "TRY" },
  { code: "TT", name: "Trinidad and Tobago", currency_code: "TTD" },
  { code: "TV", name: "Tuvalu", currency_code: "AUD" },
  { code: "TW", name: "Taiwan", currency_code: "TWD" },
  { code: "TZ", name: "Tanzania, United Republic of", currency_code: "TZS" },
  { code: "UA", name: "Ukraine", currency_code: "UAH" },
  { code: "UG", name: "Uganda", currency_code: "UGX" },
  { code: "UM", name: "United States Minor Outlying Islands", currency_code: "USD" },
  { code: "US", name: "United States", currency_code: "USD" },
  { code: "UY", name: "Uruguay", currency_code: "UYU" },
  { code: "UZ", name: "Uzbekistan", currency_code: "UZS" },
  { code: "VA", name: "Holy See", currency_code: "EUR" },
  { code: "VC", name: "Saint Vincent and the Grenadines", currency_code: "XCD" },
  { code: "VE", name: "Venezuela", currency_code: "VEB" },
  { code: "VG", name: "Virgin Islands (British)", currency_code: "USD" },
  { code: "VI", name: "Virgin Islands (U.S.)", currency_code: "USD" },
  { code: "VN", name: "Viet Nam", currency_code: "VND" },
  { code: "VU", name: "Vanuatu", currency_code: "VUV" },
  { code: "WF", name: "Wallis and Futuna", currency_code: "XPF" },
  { code: "WS", name: "Samoa", currency_code: "WST" },
  { code: "YE", name: "Yemen", currency_code: "YER" },
  { code: "YT", name: "Mayotte", currency_code: "EUR" },
  { code: "ZA", name: "South Africa", currency_code: "ZAR" },
  { code: "ZM", name: "Zambia", currency_code: "ZMW" },
  { code: "ZW", name: "Zimbabwe", currency_code: "USD" },
] as const;

export async function seedCountries() {
  const db = createDb();

  await db
    .insert(country)
    .values([...countries])
    .onConflictDoUpdate({
      target: country.code,
      set: {
        name: sql`excluded.name`,
        currency_code: sql`excluded.currency_code`,
      },
    });

  console.log(`Seeded ${countries.length} countries`);
}
