import {
  Baby,
  Banknote,
  BookOpen,
  Briefcase,
  Building,
  Bus,
  Car,
  Cat,
  Church,
  CircleDollarSign,
  CircleDot,
  Coffee,
  CreditCard,
  Dog,
  Dumbbell,
  Film,
  Flower2,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Music,
  Palette,
  PenTool,
  PiggyBank,
  Plane,
  Pizza,
  Receipt,
  Scissors,
  Shirt,
  ShoppingCart,
  Smartphone,
  Stethoscope,
  TrainFront,
  TrendingUp,
  Tv,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  type LucideIcon,
} from "lucide-react";
export const DEFAULT_CATEGORY_ICON = "circle-dot";

export const categoryIconMap: Record<string, LucideIcon> = {
  circledot: CircleDot,
  "circle-dot": CircleDot,
  shoppingcart: ShoppingCart,
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  car: Car,
  bus: Bus,
  trainfront: TrainFront,
  "train-front": TrainFront,
  plane: Plane,
  fuel: Fuel,
  home: Home,
  building: Building,
  wallet: Wallet,
  creditcard: CreditCard,
  "credit-card": CreditCard,
  banknote: Banknote,
  landmark: Landmark,
  briefcase: Briefcase,
  graduationcap: GraduationCap,
  "graduation-cap": GraduationCap,
  bookopen: BookOpen,
  "book-open": BookOpen,
  dumbbell: Dumbbell,
  heartpulse: HeartPulse,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  shirt: Shirt,
  scissors: Scissors,
  smartphone: Smartphone,
  wifi: Wifi,
  tv: Tv,
  gamepad2: Gamepad2,
  "gamepad-2": Gamepad2,
  music: Music,
  film: Film,
  gift: Gift,
  heart: Heart,
  church: Church,
  wrench: Wrench,
  hammer: Hammer,
  flower2: Flower2,
  "flower-2": Flower2,
  palette: Palette,
  pentool: PenTool,
  "pen-tool": PenTool,
  receipt: Receipt,
  piggybank: PiggyBank,
  "piggy-bank": PiggyBank,
  trendingup: TrendingUp,
  "trending-up": TrendingUp,
  circledollarsign: CircleDollarSign,
  "circle-dollar-sign": CircleDollarSign,
};

export function getCategoryIcon(iconName: string | null | undefined): LucideIcon {
  const key = iconName?.trim()
    ? iconName.toLowerCase().replace(/[-_\s]/g, "")
    : DEFAULT_CATEGORY_ICON.toLowerCase().replace(/[-_\s]/g, "");
  return categoryIconMap[key] ?? categoryIconMap[DEFAULT_CATEGORY_ICON.replace(/[-_\s]/g, "")] ?? CircleDot;
}
